# mysql config
mysql_host: 127.0.0.1
mysql_username: root
# mysql_password: root
mysql_password: cxDgTq9K
mysql_dbname: mini_tiktok
mysql_port: 3306

# redis config
redis_host: 127.0.0.1
redis_port: 6379
redis_dbname:
redis_password: 0

# logger config
# 定义从哪一级别开始打印日志，可选项为
# DEBUG(-1) INFO(0) ERROR(2)  FATAL(5)
log_level: 2
# log_format: "json"
log_format: "console"
log_time_key: "time"
log_level_key: "level"
log_name_key: "logger"
log_caller_key: "caller"
log_message_key: "msg"
log_stacktrace_key: "stacktrace"
log_path: "gin-mvc.log"
# 日志文件保存的最大尺寸, 单位：M
log_max_size: 1
# 日志文件最多保存多少天
log_max_backups: 5
# 日志文件最多保存多少个备份
log_max_age: 7
